---
- hosts: 172.31.3.236
  become: yes
  tasks: 
  - name: I want to execute linux command
    command: hostname -f
    register: taskresult

  - name: I want to print the output
    debug: 
        msg: "{{taskresult}}"

  - name: Want to install git
    apt:
      name: git
      state: present
    when: taskresult.stderr !=""
  
  - name: want to install tree
    apt:
      name: tress
      state: present
    when: taskresult.stderr ==""
