---
- hosts: 172.31.3.236
  become: yes
  tasks:
  - name: copying static files into nodes
    copy:
      src: mystaticfile
      dest: /home/ubuntu/mystaticfile
  - name: changing dynamic file
    template: 
          src: myindex.j2
          dest: /var/www/html/index.html