---
- hosts: 172.31.3.236
  become: yes
  tasks:
  - name: copying static files into nodes
    copy:
      src: mystaticfile
      dest: /home/ubuntu/mystaticfile
  - name: changing dynamic file
    template: 
          src: myindex.j2
          dest: /var/www/html/index.html
    notify: startapache

  - name: Downloading internet files
    get_url: 
         url: https://get.jenkins.io/war-stable/2.361.4/jenkins.war
         dest: /home/ubuntu
         force_basic_auth: yes

  handlers: 
  - name: startapache
    service:
         name: apache2
         state: started