---
- hosts: all
  become: yes
  tasks:
  - name: I want to install apache2 webserver
    apt:
      name: apache2
      state: present

  - name: I want to install httpd webserver
    yum:
      name: httpd
      state: present