---
- hosts: all
  become: yes
  tasks:
  - name: I want to install apache2 webserver
    apt:
      name: "{{ubuntuwebserver}}"
      state: present
    when: ansible_os_family== "Debian"

  - name: I want to install httpd webserver
    yum:
      name: "{{redhatwebserver}}"
      state: present
    when: ansible_os_family== "Redhat"