---
- hosts: all
  become: yes
  tasks:
  - name: I want to install java on ubuntu
    apt:
       name: "{{ubuntujavapack}}"
       state: present
    when: ansible_os_family=="Debian"

  - name: I want to install java on Redhat
    yum:
      name: "{{redhatjavapack}}"
      state: present
    when: ansible_os_family=="Redhat"