---
- name: add tomcat user
  template:
         src: template/mytomcat.j2
         dest: /opt/tomcat/conf/tomcat-users.xml
         
- name: add manager context file
  template:
         src: template/mytomcatcontext.j2
         dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: add host manager context file
  template:
         src: template/mytomcathostcontext.j2
         dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml