---
- name: download tomcat tar file
  get_url:
       url: https://fossies.org/linux/www/apache-tomcat-10.1.2.tar.gz/
       dest: sudo tar xzvf apache-tomcat-10*tar.gz -C /opt/tomcat --strip-components=1
       force_basic_auth: yes

- name: Creating the tomcat folder
  file:
     path: /opt/tomcat
     state: directory

- name: extract the tar files
  command:
       cmd: sudo tar xzvf apache-tomcat-10*tar.gz -C /opt/tomcat --strip-components=1
       creates: /opt/tomcat/LICENSE